[package]
name = "rtodo"
version = "0.1.0"
edition = "2021"
description = "Rusty TODO command line application."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
dirs = "5.0.1"
